version : '3'
# Launch the mysql service first, then launch the backend service
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - my_network

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    networks:
      - my_network
      - public_network
  frontend:
    build: ./daily-task-orbit
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - public_network
networks:
  my_network:
  public_network:
