# Stage 1: Build
FROM maven:3.8.5-openjdk-17-slim AS builder
WORKDIR /app
COPY . .
RUN mvn clean package

# Stage 2: Runtime
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/new_project-1.0-SNAPSHOT.jar app.jar
CMD ["java", "-jar", "app.jar"]
