name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3


      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # bring the mysql service up
      - name: Bring the Mysql service up
        run: docker-compose up -d

      # wait for 10 seconds
      - name: wait for 10s
        run: sleep 10

      # 3. Build and run tests with Maven
      - name: Build with Maven
        run: mvn clean install

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
      # 4. (Optional) Build a Docker image
      # Uncomment the following steps if you have a Dockerfile
      #- name: Build Docker Image
      #  run: docker build -t your-dockerhub-username/your-app:${{ github.sha }} .

      # 5. (Optional) Push Docker Image to GitHub Packages or DockerHub
      #- name: Log in to DockerHub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Push Docker Image
      #  run: docker push your-dockerhub-username/your-app:${{ github.sha }}
